import "OpenAIClient.idl";

namespace OpenAI
{
  [default_interface]
  runtimeclass Answer
  {
    Answer();
    Answer(String strValue);
    String Value;
    Double Confidence;
  }


  [default_interface]
  runtimeclass Context
  {
    String OriginalQuestion {get; };
    UInt32 Step{ get; };
  }

  [default_interface]
  runtimeclass EngineStepEventArgs {
      Context Context {get; };
      String EndpointName{ get; };
      String Value{ get; };
    };

  runtimeclass Engine;


  interface ISkill
  {
    String Name { get; };
    Windows.Foundation.IAsyncOperation<Answer> ExecuteAsync(String question, Context context);
    Engine Engine;
  }


  delegate Windows.Foundation.IAsyncOperation<Answer> SkillHandlerAsync(String question, Context context, Engine engine);

  [default_interface]
  runtimeclass Skill : ISkill
  {
    Skill(String name, SkillHandlerAsync handler);
  }


    [default_interface]
    runtimeclass Engine
    {
        Engine();

        Windows.Foundation.Collections.IVector<ISkill> Skills{ get; };
        ISkill GetSkill(String name);

        UInt32 MaxSteps;
        
        Windows.Foundation.IAsyncOperation<Answer> AskAsync(String query);

        event Windows.Foundation.TypedEventHandler<Engine, EngineStepEventArgs> EngineStepSend;
        event Windows.Foundation.TypedEventHandler<Engine, EngineStepEventArgs> EngineStepReceive;

        void ConnectSkills();
    }

}
