import "Choice.idl";
import "CompletionRequest.idl";
import "PromptTemplate.idl";
import "Engine.idl";

namespace OpenAI
{
    [default_interface]
    runtimeclass OpenAIClient : ISkill
    {
        OpenAIClient();
        String ApiKey;
        Windows.Foundation.Uri CompletionUri;

        Boolean UseBearerTokenAuthorization;
        
        
        Windows.Foundation.IAsyncOperation< Windows.Foundation.Collections.IVector<Choice> > GetCompletionAsync(String prompt, String model);
        Windows.Foundation.IAsyncOperation< Windows.Foundation.Collections.IVector<Choice> > GetCompletionAsync(CompletionRequest request);
        
        PromptTemplate CreateTemplate(String prompt);
        FewShotTemplate CreateFewShotTemplate(Windows.Foundation.Collections.IVectorView<String> parameters);

        
    }
}
