import "Engine.idl";

namespace OpenAI
{
    [default_interface]
    runtimeclass SearchEndpoint : ISkill
    {
        SearchEndpoint();
        String ApiKey;
        String Market;

        Engine Engine;
    }
}
