import "Engine.idl";

namespace OpenAI
{
    [default_interface]
    runtimeclass SearchEndpoint 
    {
        SearchEndpoint();
        String ApiKey;
        String Market;
        Windows.Foundation.IAsyncOperation<Windows.Data.Json.JsonObject> SearchAsync(String query);
    }


  [default_interface]
  runtimeclass SearchSkill : ISkill
  {
    SearchSkill(SearchEndpoint Endpoint);
  }

}
